name: publish-to-self-hosted

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: false

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit --progress=false

      - name: Build Next.js app
        run: npm run build

      - name: Run app
        run: npm start
